export interface IPostulacion {
    estado?: string,
    id_postulacion: string,
    categoria: string,
    mencion: string,
    titulo: string,
    departamento: string,
    provincia: string,
    distrito: string,
    localidad: string,
    direccion: string,
    tipo_persona: string,
    tipo_experiencia: string,
    nombre_completo: string,
    nom_representante: string,
    cargo_postulante: string,
    telefono: string,
    email: string,
    red_social_postulante: string,
    numero_documento: string,
    domicilio?: string,
    domicilio_legal: string,
    nombre_organizacion: string,
    breve_resumen: string,
    obj_postulacion: string,
    inclusion_postulacion: string,
    sostenibilidad_postulacion: string,
    replicabilidad_postulacion: string,
    link_video: string,
    link_video1: string,
    link_video2: string,
    link_video3: string,
    link_video4: string,
    nombre_postulante_declara: string,
    tipo_number_doc_declara: string,
    direccion_postulante_declara: string,
    cantidad_documentos: string,
    sitio_web_postulante: string,
    aceptacion_declara?: any
}

// 1 = en proceso
// 2 = finalizado